version: "3.0"
services:
  server-eureka:
    build:
      context: ./roncoo-education-server-eureka
      args:
        JAVA_OPTS: '-Xmn128M -Xmx128M'
        RUN_ARGS: '--spring.profiles.active=dev'
    image: roncoo-education-server-eureka
    container_name: eureka
    restart: always
    volumes:
      - /home/roncoo/dockers/logs/eureka:/home/roncoo/education/logs/eureka
    networks:
      - education
    ports:
      - "5761:5761"
  server-config:
    build:
      context: ./roncoo-education-server-config
      args:
        JAVA_OPTS: '-Xmn128M -Xmx128M'
        RUN_ARGS: '--spring.profiles.active=native --info.eureka.host=server-eureka'
    image: roncoo-education-server-config
    container_name: config
    restart: always
    volumes:
      - /home/roncoo/dockers/logs/config:/home/roncoo/education/logs/config
    networks:
      - education
    ports:
      - "5741:5741"
    depends_on:
      - server-eureka
    links:
      - server-eureka
  server-sba:
    build:
      context: ./roncoo-education-server-sba
      args:
        JAVA_OPTS: '-Xmn128M -Xmx128M'
        RUN_ARGS: '--spring.profiles.active=dev --info.eureka.host=server-eureka'
    image: roncoo-education-server-sba
    container_name: sba
    restart: always
    volumes:
      - /home/roncoo/dockers/logs/sba:/home/roncoo/education/logs/sba
    networks:
      - education
    ports:
      - "5721:5721"
    depends_on:
      - server-config
    links:
      - server-eureka
  server-job:
    build:
      context: ./roncoo-education-server-job
      args:
        JAVA_OPTS: '-Xmn128M -Xmx128M'
        RUN_ARGS: '--spring.profiles.active=dev --info.eureka.host=server-eureka'
    image: roncoo-education-server-job
    container_name: job
    restart: always
    volumes:
      - /home/roncoo/dockers/logs/job:/home/roncoo/education/logs/job
    networks:
      - education
    ports:
      - "5820:5820"
    depends_on:
      - server-config
    links:
      - server-eureka
  server-gateway:
    build:
      context: ./roncoo-education-server-gateway
      args:
        JAVA_OPTS: '-Xmn128M -Xmx128M'
        RUN_ARGS: '--spring.profiles.active=dev --info.eureka.host=server-eureka'
    image: roncoo-education-server-gateway
    container_name: gateway
    restart: always
    volumes:
      - /home/roncoo/dockers/logs/gateway:/home/roncoo/education/logs/gateway
    networks:
      - education
    ports:
      - "5840:5840"
    depends_on:
      - server-config
    links:
      - server-eureka
  system-service:
    build:
      context: ./roncoo-education-system/roncoo-education-system-service
      args:
        JAVA_OPTS: '-Xmn128M -Xmx128M'
        RUN_ARGS: '--spring.profiles.active=dev --info.eureka.host=server-eureka'
    image: roncoo-education-system-service
    container_name: system
    restart: always
    volumes:
      - /home/roncoo/dockers/logs/system:/home/roncoo/education/logs/system
    networks:
      - education
    ports:
      - "5730:5730"
    depends_on:
      - server-gateway
    links:
      - server-eureka
  user-service:
    build:
      context: ./roncoo-education-user/roncoo-education-user-service
      args:
        JAVA_OPTS: '-Xmn128M -Xmx128M'
        RUN_ARGS: '--spring.profiles.active=dev --info.eureka.host=server-eureka'
    image: roncoo-education-user-service
    container_name: user
    restart: always
    volumes:
      - /home/roncoo/dockers/logs/user:/home/roncoo/education/logs/user
    networks:
      - education
    ports:
      - "5720:5720"
    depends_on:
      - server-gateway
    links:
      - server-eureka
  course-service:
    build:
      context: ./roncoo-education-course/roncoo-education-course-service
      args:
        JAVA_OPTS: '-Xmn128M -Xmx128M'
        RUN_ARGS: '--spring.profiles.active=dev --info.eureka.host=server-eureka'
    image: roncoo-education-course-service
    container_name: course
    restart: always
    volumes:
      - /home/roncoo/dockers/logs/course:/home/roncoo/education/logs/course
    networks:
      - education
    ports:
      - "5710:5710"
    depends_on:
      - server-gateway
    links:
      - server-eureka
networks:
  education:
    driver: bridge
